### ISSUE TITLE
Please don't provide the feature 'env'

### ISSUE THREAD

**Issue by tarsius** [micdahl/projectile-trailblazer#1]
Emacs comes with a library that provides that feature. If you provide it too, then your unrelated library might get loaded instead.

Please rename the file to `projectile-trailblazer-env` or if that is not possible (I am not familiar with Cask), then add the file `features/.nosearch` to prevent that directory and its subdirectories from being added to the `load-path`. If you do the latter, then you should also remove `(provide 'env)` -- that seems unnecessary anyway, nothing does `(require 'env)` in your package.

**Comment by micdahl** [comment]
Thank you!
Have done the second, because [Ecukes](https://github.com/ecukes/ecukes) needs this file named `.env`.

**Comment by tarsius** [comment]
Thanks!
